import superagent from 'superagent';
import fs from 'fs';

// 00000
// ABCDE,AUX
// each bit represents a different argument
enum OpMode {
    None = 0b00000,
    A = 0b10000,
    AB = 0b11000,
    AC = 0b10100,
    ABC = 0b11100,
    AD = 0b10010,
    D = 0b00010,
    //AE = 0b10001,
    E = 0b00001,
}

interface Opcode {
    name: string; // the name of the opcode
    mode: number; // the mode of the opcode
    opcode: number; // the opcode value
    hasAUX: boolean; // does the opcode have an AUX value?
}

async function main() {

    let req = await superagent.get("https://raw.githubusercontent.com/luau-lang/luau/master/Common/include/Luau/Bytecode.h");

    const AllOpcodes: Opcode[] = [];

    let lines = req.text.split("\n");
    let hasBegunOpcodes = false;
    let TotalOpcodes = 0;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].includes("enum LuauOpcode")) // the beginning of the opcodes
        {
            hasBegunOpcodes = true;
            i++ // skip the { character
            continue;
        }

        if (hasBegunOpcodes && lines[i].includes("}")) // the end of the opcodes
        {
            console.log("Found the end of the opcodes");
            break;
        }

        if (!hasBegunOpcodes) continue;
        // we are in the OpCodes!

        // remove beginning whitespace
        let line = lines[i].trim();

        if (line.startsWith("LOP_")) {
            let opCode = line.split(",")[0]

            let Desc = "";
            let argNumber = 0b000000;

            let currentLine = i;
            let hasFoundOPDescription = false;
            while (!hasFoundOPDescription) {
                currentLine--;
                let line = lines[currentLine].trim();

                if (line == "" || line.includes("{")) {
                    hasFoundOPDescription = true;
                    Desc = lines[currentLine + 1].trim().split("// ")[1].trim();
                }

                // ABCDE + AUX
                if (line.includes("// A:")) argNumber += 0b1000000;
                if (line.includes("// B:")) argNumber += 0b0100000;
                if (line.includes("// C:")) argNumber += 0b0010000;
                if (line.includes("// D:")) argNumber += 0b0001000;
                if (line.includes("// E:")) argNumber += 0b0000100;
                // cus we can have two AUX values
                if (line.includes("// AUX:")){
                    if (argNumber & 0b0000010)
                    {
                        argNumber += 0b0000001
                    } else {
                        argNumber += 0b0000010
                    }

                }

            }

            if (OpMode[argNumber>>2] == undefined){
                console.warn("Invalid argument mode for opcode " + opCode);
            }

            let op = {
                name: opCode,
                mode: argNumber,
                opcode: AllOpcodes.length,
                hasAUX: ((argNumber & 0b0000001) == 0b0000001) || ((argNumber & 0b0000010) == 0b0000010)
            } as Opcode

            AllOpcodes.push(op);
            console.log(op.opcode,": Found opcode: " + opCode + ":", OpMode[argNumber>>2], "Has Aux?:", op.hasAUX);

        }

    }

    let OpCodeFile = `// This file is generated by generateOp.ts\n`
    function writeLine(line: string) {OpCodeFile += line + "\n"};

    writeLine(`// Generated at ${new Date().toUTCString()}`);
    writeLine(`export const OpCodeNames = [`);
    for (let op of AllOpcodes) {
        writeLine(`    "${op.name.split("_")[1]}",`);
    }
    writeLine(`]`);
    writeLine(``)
    writeLine(`export const OpCodeModes = [`);
    for (let op of AllOpcodes) {
        writeLine(`    ${op.mode},`);
    }
    writeLine(`]`);

    fs.writeFileSync("./OpCodes.ts", OpCodeFile);
}

main();