// This file is generated by generateOp.ts
// Generated at Thu, 08 Aug 2024 06:47:53 GMT
export const OpCodeNames = [
    "NOP", // OP: 0
    "BREAK", // OP: 1
    "LOADNIL", // OP: 2
    "LOADB", // OP: 3
    "LOADN", // OP: 4
    "LOADK", // OP: 5
    "MOVE", // OP: 6
    "GETGLOBAL", // OP: 7
    "SETGLOBAL", // OP: 8
    "GETUPVAL", // OP: 9
    "SETUPVAL", // OP: 10
    "CLOSEUPVALS", // OP: 11
    "GETIMPORT", // OP: 12
    "GETTABLE", // OP: 13
    "SETTABLE", // OP: 14
    "GETTABLEKS", // OP: 15
    "SETTABLEKS", // OP: 16
    "GETTABLEN", // OP: 17
    "SETTABLEN", // OP: 18
    "NEWCLOSURE", // OP: 19
    "NAMECALL", // OP: 20
    "CALL", // OP: 21
    "RETURN", // OP: 22
    "JUMP", // OP: 23
    "JUMPBACK", // OP: 24
    "JUMPIF", // OP: 25
    "JUMPIFNOT", // OP: 26
    "JUMPIFEQ", // OP: 27
    "JUMPIFLE", // OP: 28
    "JUMPIFLT", // OP: 29
    "JUMPIFNOTEQ", // OP: 30
    "JUMPIFNOTLE", // OP: 31
    "JUMPIFNOTLT", // OP: 32
    "ADD", // OP: 33
    "SUB", // OP: 34
    "MUL", // OP: 35
    "DIV", // OP: 36
    "MOD", // OP: 37
    "POW", // OP: 38
    "ADDK", // OP: 39
    "SUBK", // OP: 40
    "MULK", // OP: 41
    "DIVK", // OP: 42
    "MODK", // OP: 43
    "POWK", // OP: 44
    "AND", // OP: 45
    "OR", // OP: 46
    "ANDK", // OP: 47
    "ORK", // OP: 48
    "CONCAT", // OP: 49
    "NOT", // OP: 50
    "MINUS", // OP: 51
    "LENGTH", // OP: 52
    "NEWTABLE", // OP: 53
    "DUPTABLE", // OP: 54
    "SETLIST", // OP: 55
    "FORNPREP", // OP: 56
    "FORNLOOP", // OP: 57
    "FORGLOOP", // OP: 58
    "FORGPREP_INEXT", // OP: 59
    "FASTCALL3", // OP: 60
    "FORGPREP_NEXT", // OP: 61
    "NATIVECALL", // OP: 62
    "GETVARARGS", // OP: 63
    "DUPCLOSURE", // OP: 64
    "PREPVARARGS", // OP: 65
    "LOADKX", // OP: 66
    "JUMPX", // OP: 67
    "FASTCALL", // OP: 68
    "COVERAGE", // OP: 69
    "CAPTURE", // OP: 70
    "SUBRK", // OP: 71
    "DIVRK", // OP: 72
    "FASTCALL1", // OP: 73
    "FASTCALL2", // OP: 74
    "FASTCALL2K", // OP: 75
    "FORGPREP", // OP: 76
    "JUMPXEQKNIL", // OP: 77
    "JUMPXEQKB", // OP: 78
    "JUMPXEQKN", // OP: 79
    "JUMPXEQKS", // OP: 80
    "IDIV", // OP: 81
    "IDIVK", // OP: 82
    "_COUNT", // OP: 83
]

export enum OpCode {
    NOP = 0,
    BREAK = 1,
    LOADNIL = 2,
    LOADB = 3,
    LOADN = 4,
    LOADK = 5,
    MOVE = 6,
    GETGLOBAL = 7,
    SETGLOBAL = 8,
    GETUPVAL = 9,
    SETUPVAL = 10,
    CLOSEUPVALS = 11,
    GETIMPORT = 12,
    GETTABLE = 13,
    SETTABLE = 14,
    GETTABLEKS = 15,
    SETTABLEKS = 16,
    GETTABLEN = 17,
    SETTABLEN = 18,
    NEWCLOSURE = 19,
    NAMECALL = 20,
    CALL = 21,
    RETURN = 22,
    JUMP = 23,
    JUMPBACK = 24,
    JUMPIF = 25,
    JUMPIFNOT = 26,
    JUMPIFEQ = 27,
    JUMPIFLE = 28,
    JUMPIFLT = 29,
    JUMPIFNOTEQ = 30,
    JUMPIFNOTLE = 31,
    JUMPIFNOTLT = 32,
    ADD = 33,
    SUB = 34,
    MUL = 35,
    DIV = 36,
    MOD = 37,
    POW = 38,
    ADDK = 39,
    SUBK = 40,
    MULK = 41,
    DIVK = 42,
    MODK = 43,
    POWK = 44,
    AND = 45,
    OR = 46,
    ANDK = 47,
    ORK = 48,
    CONCAT = 49,
    NOT = 50,
    MINUS = 51,
    LENGTH = 52,
    NEWTABLE = 53,
    DUPTABLE = 54,
    SETLIST = 55,
    FORNPREP = 56,
    FORNLOOP = 57,
    FORGLOOP = 58,
    FORGPREP_INEXT = 59,
    FASTCALL3 = 60,
    FORGPREP_NEXT = 61,
    NATIVECALL = 62,
    GETVARARGS = 63,
    DUPCLOSURE = 64,
    PREPVARARGS = 65,
    LOADKX = 66,
    JUMPX = 67,
    FASTCALL = 68,
    COVERAGE = 69,
    CAPTURE = 70,
    SUBRK = 71,
    DIVRK = 72,
    FASTCALL1 = 73,
    FASTCALL2 = 74,
    FASTCALL2K = 75,
    FORGPREP = 76,
    JUMPXEQKNIL = 77,
    JUMPXEQKB = 78,
    JUMPXEQKN = 79,
    JUMPXEQKS = 80,
    IDIV = 81,
    IDIVK = 82,
    _COUNT = 83,
}

export const OpCodeModes = [
    0,
    0,
    64,
    112,
    72,
    72,
    96,
    82,
    82,
    96,
    96,
    64,
    74,
    112,
    112,
    114,
    114,
    112,
    112,
    72,
    114,
    112,
    96,
    8,
    8,
    72,
    72,
    74,
    74,
    74,
    74,
    74,
    74,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    112,
    96,
    96,
    96,
    98,
    72,
    114,
    72,
    72,
    74,
    72,
    115,
    72,
    0,
    96,
    72,
    64,
    66,
    4,
    80,
    4,
    96,
    112,
    112,
    112,
    114,
    114,
    72,
    74,
    74,
    74,
    74,
    112,
    112,
    0,
]
